name: jazzcash_flutter
description: JazzCash Payment gateway integration in Flutter projects.
version: 1.0.0
homepage: https://github.com/mabdullahjan/jazzcash_flutter

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
